### ISSUE TITLE
Innsláttarvillur

### ISSUE THREAD

**Issue by snaeja13** [HI-IDN/IDN302G-GitBook#2]
-Sýnist vera innsláttarvilla í kaflaheitinu ,,_samsöfnum og hópun_", sem er að finna undir  **SQL grunnatriði** , tel að það eigi að vera samsöfnun og hópun. Er aftur skrifað á sama hátt undir kaflanum **æfingar** sem er undir **SQL grunnatriði**.

-Undir kaflanum **Grunn SQL fyrirspurnir** finnst setningin: _Hér koma sýnidæmi með SQL fyrirspurnum fyrir SQLite gangagrunn._ , gangagrunn ætti að vera gagnagrunn.

-

**Comment by tungufoss** [comment]
Vel spottað. Mátt endilega enduropna og láta mig vita ef þú finnur fleiri.
